### ISSUE TITLE
[Explore] Category gives wrong pagination

### ISSUE THREAD

**Issue by marcusngwj** [CS2102Group18/CS2102#114]
![image](https://user-images.githubusercontent.com/13817632/47600649-73ef1d00-d9f7-11e8-9604-d04dfcae3141.png)

Correct result, but wrong pagination. If click the pagination, it gave results that shouldn't be shown
It will show the page 2 of the entire database
![image](https://user-images.githubusercontent.com/13817632/47600669-ae58ba00-d9f7-11e8-823f-23792eff4a9b.png)

**Comment by dylansyj** [comment]
I think i know what's the problem liao. Because current pagination implementation takes in total no. of projects and splits accordingly. hmm...
