### ISSUE TITLE
[Admin] Add more functionalities

### ISSUE THREAD

**Issue by marcusngwj** [CS2102Group18/CS2102#75]
## User Management
- [x] Allow admin to update user personal information via admin page
- [x] Allow admin to create new user via admin page

## Project Management
- [x] Allow admin to delete project
- [x] Allow admin to create project (While creating, allow admin to set who is the entrepreneur)
- [x] Allow admin to update project details (Except amount raised)

**Comment by dylansyj** [comment]
Added restriction to updating project details
1) Cant edit id (primary key)
2) Cant edit status (dependent on amount_raised == amount_needed)
3) Start date ( TBD )
